# Generated by Django 5.0.3 on 2025-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('paypal', 'PayPal')], max_length=20, null=True),
        ),
    ]
